# Form implementation generated from reading ui file 'Bai6_SecondWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QLabel, QLineEdit, QPushButton


class SecondWindow(object):
    def __init__(self,parent):
        self.parent=parent
    def setupUi(self, MainWindow):
        self.MainWindow=MainWindow
        self.MainWindow.setObjectName("SecondWindow")
        MainWindow.resize(453, 219)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 131, 31))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 221, 31))
        self.lineEdit.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonRed = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRed.setGeometry(QtCore.QRect(90, 110, 56, 17))
        self.pushButtonRed.setObjectName("pushButtonRed")
        self.pushButtonYellow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonYellow.setGeometry(QtCore.QRect(170, 110, 56, 17))
        self.pushButtonYellow.setObjectName("pushButtonYellow")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(250, 110, 56, 17))
        self.pushButtonClose.setObjectName("pushButtonClose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.lineEdit.setText(self.parent.lineEditName.text())
        self.lineEdit.textChanged.connect(self.parent.lineEditName.setText)
        self.pushButtonClose.clicked.connect(self.processClose) # type: ignore
        self.pushButtonRed.clicked.connect(self.changeRed)
        self.pushButtonYellow.clicked.connect(self.changeYellow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Change Name"))
        self.pushButtonRed.setText(_translate("MainWindow", "Red"))
        self.pushButtonYellow.setText(_translate("MainWindow", "Yellow"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
    def processClose(self):
        self.MainWindow.close()
        self.parent.secondWindow=None
    def changeRed(self):
        self.MainWindow.setStyleSheet("background-color: red;")
    def changeYellow(self):
        self.MainWindow.setStyleSheet("background-color: yellow;")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = SecondWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
