# Form implementation generated from reading ui file 'MainWindow21.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.ChinhhopTohop = QtWidgets.QLabel(parent=Dialog)
        self.ChinhhopTohop.setGeometry(QtCore.QRect(110, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ChinhhopTohop.setFont(font)
        self.ChinhhopTohop.setStyleSheet("color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.ChinhhopTohop.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.ChinhhopTohop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ChinhhopTohop.setObjectName("ChinhhopTohop")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(90, 60, 221, 81))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.nhapN = QtWidgets.QLabel(parent=self.groupBox)
        self.nhapN.setGeometry(QtCore.QRect(20, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.nhapN.setFont(font)
        self.nhapN.setStyleSheet("font: 75 15pt \"Times New Roman\";")
        self.nhapN.setObjectName("nhapN")
        self.nhapK = QtWidgets.QLabel(parent=self.groupBox)
        self.nhapK.setGeometry(QtCore.QRect(20, 50, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.nhapK.setFont(font)
        self.nhapK.setStyleSheet("font: 75 15pt \"Times New Roman\";")
        self.nhapK.setObjectName("nhapK")
        self.nhapn = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nhapn.setGeometry(QtCore.QRect(110, 20, 101, 20))
        self.nhapn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 15pt \"Times New Roman\";")
        self.nhapn.setObjectName("nhapn")
        self.nhapk = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nhapk.setGeometry(QtCore.QRect(110, 50, 101, 20))
        self.nhapk.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 15pt \"Times New Roman\";")
        self.nhapk.setObjectName("nhapk")
        self.thuchien = QtWidgets.QPushButton(parent=Dialog)
        self.thuchien.setGeometry(QtCore.QRect(150, 150, 91, 31))
        self.thuchien.setStyleSheet("font: 75 italic 15pt \"Times New Roman\";")
        self.thuchien.setObjectName("thuchien")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(90, 190, 221, 81))
        self.groupBox_2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.nhapN_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.nhapN_2.setGeometry(QtCore.QRect(20, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.nhapN_2.setFont(font)
        self.nhapN_2.setStyleSheet("font: 75 15pt \"Times New Roman\";")
        self.nhapN_2.setObjectName("nhapN_2")
        self.nhapK_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.nhapK_2.setGeometry(QtCore.QRect(20, 50, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.nhapK_2.setFont(font)
        self.nhapK_2.setStyleSheet("font: 75 15pt \"Times New Roman\";")
        self.nhapK_2.setObjectName("nhapK_2")
        self.ansA = QtWidgets.QKeySequenceEdit(parent=self.groupBox_2)
        self.ansA.setGeometry(QtCore.QRect(112, 20, 101, 20))
        self.ansA.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 15pt \"Times New Roman\";")
        self.ansA.setObjectName("ansA")
        self.ansC = QtWidgets.QKeySequenceEdit(parent=self.groupBox_2)
        self.ansC.setGeometry(QtCore.QRect(110, 50, 101, 20))
        self.ansC.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 italic 15pt \"Times New Roman\";")
        self.ansC.setObjectName("ansC")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Nguyễn Như Quỳnh 798 - Chỉnh hợp Tổ hợp"))
        self.ChinhhopTohop.setText(_translate("Dialog", "Chỉnh hợp - Tổ hợp"))
        self.groupBox.setTitle(_translate("Dialog", "Nhập N và K"))
        self.nhapN.setText(_translate("Dialog", "Nhập N"))
        self.nhapK.setText(_translate("Dialog", "Nhập K"))
        self.thuchien.setText(_translate("Dialog", "Thực hiện"))
        self.groupBox_2.setTitle(_translate("Dialog", "Kết quả"))
        self.nhapN_2.setText(_translate("Dialog", "Chỉnh hợp A"))
        self.nhapK_2.setText(_translate("Dialog", "Tổ hợp C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
