# Form implementation generated from reading ui file 'MainWindow21.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NguyenNhuQuynh_798_TohopChinhhop(object):
    def setupUi(self, NguyenNhuQuynh_798_TohopChinhhop):
        NguyenNhuQuynh_798_TohopChinhhop.setObjectName("NguyenNhuQuynh_798_TohopChinhhop")
        NguyenNhuQuynh_798_TohopChinhhop.resize(280, 315)
        self.centralwidget = QtWidgets.QWidget(parent=NguyenNhuQuynh_798_TohopChinhhop)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"color: rgb(255, 170, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 251, 81))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: italic 13pt \"Times New Roman\";")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 81, 21))
        self.label_2.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_3.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.nhapN = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nhapN.setGeometry(QtCore.QRect(110, 20, 131, 20))
        self.nhapN.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.nhapN.setText("")
        self.nhapN.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nhapN.setObjectName("nhapN")
        self.nhapK = QtWidgets.QLineEdit(parent=self.groupBox)
        self.nhapK.setGeometry(QtCore.QRect(110, 50, 131, 20))
        self.nhapK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.nhapK.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nhapK.setObjectName("nhapK")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 251, 81))
        self.groupBox_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: italic 13pt \"Times New Roman\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 71, 21))
        self.label_4.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 71, 21))
        self.label_5.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.chinhhopP = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.chinhhopP.setGeometry(QtCore.QRect(110, 20, 131, 20))
        self.chinhhopP.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.chinhhopP.setText("")
        self.chinhhopP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chinhhopP.setObjectName("chinhhopP")
        self.tohopC = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.tohopC.setGeometry(QtCore.QRect(110, 50, 131, 20))
        self.tohopC.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.tohopC.setText("")
        self.tohopC.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tohopC.setObjectName("tohopC")
        self.thuchien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.thuchien.setGeometry(QtCore.QRect(80, 140, 121, 31))
        self.thuchien.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calculator.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.thuchien.setIcon(icon)
        self.thuchien.setObjectName("thuchien")
        NguyenNhuQuynh_798_TohopChinhhop.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NguyenNhuQuynh_798_TohopChinhhop)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 280, 18))
        self.menubar.setObjectName("menubar")
        NguyenNhuQuynh_798_TohopChinhhop.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NguyenNhuQuynh_798_TohopChinhhop)
        self.statusbar.setObjectName("statusbar")
        NguyenNhuQuynh_798_TohopChinhhop.setStatusBar(self.statusbar)

        self.retranslateUi(NguyenNhuQuynh_798_TohopChinhhop)
        QtCore.QMetaObject.connectSlotsByName(NguyenNhuQuynh_798_TohopChinhhop)

    def retranslateUi(self, NguyenNhuQuynh_798_TohopChinhhop):
        _translate = QtCore.QCoreApplication.translate
        NguyenNhuQuynh_798_TohopChinhhop.setWindowTitle(_translate("NguyenNhuQuynh_798_TohopChinhhop", "MainWindow"))
        self.label.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "CHỈNH HỢP - TỔ HỢP"))
        self.groupBox.setTitle(_translate("NguyenNhuQuynh_798_TohopChinhhop", "Nhập N và K"))
        self.label_2.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "Nhập N"))
        self.label_3.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "Nhập K"))
        self.groupBox_2.setTitle(_translate("NguyenNhuQuynh_798_TohopChinhhop", "Kết quả"))
        self.label_4.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "A   ="))
        self.label_5.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "C   = "))
        self.thuchien.setText(_translate("NguyenNhuQuynh_798_TohopChinhhop", "Thực hiện"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NguyenNhuQuynh_798_TohopChinhhop = QtWidgets.QMainWindow()
    ui = Ui_NguyenNhuQuynh_798_TohopChinhhop()
    ui.setupUi(NguyenNhuQuynh_798_TohopChinhhop)
    NguyenNhuQuynh_798_TohopChinhhop.show()
    sys.exit(app.exec())
