# Form implementation generated from reading ui file 'd:\Ky_thuat_lap_trình\Exercise\GiaodienCoban_Blogx8\Bai15\Bai15.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 339)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButtonRed = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonRed.setGeometry(QtCore.QRect(70, 30, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButtonRed.setFont(font)
        self.radioButtonRed.setObjectName("radioButtonRed")
        self.radioButtonGreen = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonGreen.setGeometry(QtCore.QRect(70, 80, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButtonGreen.setFont(font)
        self.radioButtonGreen.setObjectName("radioButtonGreen")
        self.radioButtonBlue = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonBlue.setGeometry(QtCore.QRect(70, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radioButtonBlue.setFont(font)
        self.radioButtonBlue.setObjectName("radioButtonBlue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButtonRed.setText(_translate("MainWindow", "Red"))
        self.radioButtonGreen.setText(_translate("MainWindow", "Green"))
        self.radioButtonBlue.setText(_translate("MainWindow", "Blue"))
