# Form implementation generated from reading ui file 'd:\Ky_thuat_lap_trình\Exercise\GiaodienCoban_Blogx8\Bai11\Bai11.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 460)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 50, 221, 41))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 251, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 100, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 100, 56, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 100, 56, 17))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 100, 56, 17))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(400, 100, 56, 17))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButtonJPG = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonJPG.setGeometry(QtCore.QRect(50, 130, 131, 21))
        self.pushButtonJPG.setObjectName("pushButtonJPG")
        self.pushButtonGIF = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonGIF.setGeometry(QtCore.QRect(260, 130, 131, 21))
        self.pushButtonGIF.setObjectName("pushButtonGIF")
        self.JPG = QtWidgets.QLabel(parent=self.centralwidget)
        self.JPG.setGeometry(QtCore.QRect(120, 170, 200, 200))
        self.JPG.setMinimumSize(QtCore.QSize(200, 200))
        self.JPG.setMaximumSize(QtCore.QSize(200, 200))
        self.JPG.setText("")
        self.JPG.setPixmap(QtGui.QPixmap("d:\\Ky_thuat_lap_trình\\Exercise\\GiaodienCoban_Blogx8\\Bai11\\Logo UEL.jpg"))
        self.JPG.setScaledContents(True)
        self.JPG.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.JPG.setObjectName("JPG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonJPG.clicked.connect(self.JPG.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#55aaff;\">Trường Đại học Kinh tế - Luật</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#55aaff;\">Trường Đại học Kinh tế - Luật</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Change Text"))
        self.pushButton_2.setText(_translate("MainWindow", "Font Size ++"))
        self.pushButton_3.setText(_translate("MainWindow", "Align Left"))
        self.pushButton_4.setText(_translate("MainWindow", "Align Center"))
        self.pushButton_5.setText(_translate("MainWindow", "Align Center"))
        self.pushButtonJPG.setText(_translate("MainWindow", "Show .JPG Format"))
        self.pushButtonGIF.setText(_translate("MainWindow", "Show .GIF Format"))
