from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 462)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 50, 211, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.gridLayoutWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 181, 113))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.catalogueIDLabel_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.catalogueIDLabel_2.setObjectName("catalogueIDLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.catalogueIDLabel_2)
        self.LineEditProductID = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEditProductID.setObjectName("LineEditProductID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditProductID)
        self.catalogueNameLabel_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.catalogueNameLabel_2.setObjectName("catalogueNameLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.catalogueNameLabel_2)
        self.LineEditProductName = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEditProductName.setObjectName("LineEditProductName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditProductName)
        self.priceLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceLabel)
        self.LineEditProductPrice = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEditProductPrice.setObjectName("LineEditProductPrice")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditProductPrice)
        self.originLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.originLabel.setObjectName("originLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.originLabel)
        self.LineEditProductOrigin = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEditProductOrigin.setObjectName("LineEditProductOrigin")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditProductOrigin)
        self.inStockLabel = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.inStockLabel.setObjectName("inStockLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inStockLabel)
        self.LineEditInStock = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.LineEditInStock.setObjectName("LineEditInStock")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditInStock)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 120, 181, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonProductSave = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.pushButtonProductSave.setObjectName("pushButtonProductSave")
        self.horizontalLayout_4.addWidget(self.pushButtonProductSave)
        self.pushButtonProductRemove = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_3)
        self.pushButtonProductRemove.setObjectName("pushButtonProductRemove")
        self.horizontalLayout_4.addWidget(self.pushButtonProductRemove)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.gridLayoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(200, 100))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 44))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.catalogueIDLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.catalogueIDLabel.setObjectName("catalogueIDLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.catalogueIDLabel)
        self.LineEditCatalogueID = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEditCatalogueID.setObjectName("LineEditCatalogueID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditCatalogueID)
        self.catalogueNameLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.catalogueNameLabel.setObjectName("catalogueNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.catalogueNameLabel)
        self.LineEditCatalogueName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.LineEditCatalogueName.setObjectName("LineEditCatalogueName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditCatalogueName)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 181, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonCatalogueSave = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButtonCatalogueSave.setObjectName("pushButtonCatalogueSave")
        self.horizontalLayout_3.addWidget(self.pushButtonCatalogueSave)
        self.pushButtonCatalogueRemove = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.pushButtonCatalogueRemove.setObjectName("pushButtonCatalogueRemove")
        self.horizontalLayout_3.addWidget(self.pushButtonCatalogueRemove)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.gridLayoutWidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.groupBox_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 181, 51))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.LineEditTotalValue = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.LineEditTotalValue.setMaximumSize(QtCore.QSize(100, 19))
        self.LineEditTotalValue.setObjectName("LineEditTotalValue")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditTotalValue)
        self.LineEditListByOrigin = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.LineEditListByOrigin.setMaximumSize(QtCore.QSize(120, 16777215))
        self.LineEditListByOrigin.setObjectName("LineEditListByOrigin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.LineEditListByOrigin)
        self.pushButtonTotalValue = QtWidgets.QPushButton(parent=self.formLayoutWidget_3)
        self.pushButtonTotalValue.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonTotalValue.setObjectName("pushButtonTotalValue")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButtonTotalValue)
        self.pushButtonListByOrigin = QtWidgets.QPushButton(parent=self.formLayoutWidget_3)
        self.pushButtonListByOrigin.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButtonListByOrigin.setObjectName("pushButtonListByOrigin")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pushButtonListByOrigin)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(240, 50, 240, 111))
        self.scrollArea.setMaximumSize(QtCore.QSize(240, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 238, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelCatalogueList = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelCatalogueList.setMaximumSize(QtCore.QSize(240, 20))
        self.labelCatalogueList.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.labelCatalogueList.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCatalogueList.setObjectName("labelCatalogueList")
        self.verticalLayout_4.addWidget(self.labelCatalogueList)
        self.verticalLayoutCatalogue = QtWidgets.QVBoxLayout()
        self.verticalLayoutCatalogue.setObjectName("verticalLayoutCatalogue")
        self.verticalLayout_4.addLayout(self.verticalLayoutCatalogue)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(240, 170, 240, 241))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(240, 16777215))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 238, 239))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelProductList = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.labelProductList.setMaximumSize(QtCore.QSize(240, 20))
        self.labelProductList.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelProductList.setObjectName("labelProductList")
        self.verticalLayout_3.addWidget(self.labelProductList)
        self.verticalLayoutProduct = QtWidgets.QVBoxLayout()
        self.verticalLayoutProduct.setObjectName("verticalLayoutProduct")
        self.verticalLayout_3.addLayout(self.verticalLayoutProduct)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Product"))
        self.catalogueIDLabel_2.setText(_translate("MainWindow", "ID"))
        self.catalogueNameLabel_2.setText(_translate("MainWindow", "Name"))
        self.priceLabel.setText(_translate("MainWindow", "Price"))
        self.originLabel.setText(_translate("MainWindow", "Origin"))
        self.inStockLabel.setText(_translate("MainWindow", "In stock"))
        self.pushButtonProductSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonProductRemove.setText(_translate("MainWindow", "Remove"))
        self.groupBox.setTitle(_translate("MainWindow", "Catalogue"))
        self.catalogueIDLabel.setText(_translate("MainWindow", "ID"))
        self.catalogueNameLabel.setText(_translate("MainWindow", "Name"))
        self.pushButtonCatalogueSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonCatalogueRemove.setText(_translate("MainWindow", "Remove"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Function"))
        self.pushButtonTotalValue.setText(_translate("MainWindow", "Total Product Value"))
        self.pushButtonListByOrigin.setText(_translate("MainWindow", "List by Origin:"))
        self.labelCatalogueList.setText(_translate("MainWindow", "Catalogue List"))
        self.labelProductList.setText(_translate("MainWindow", "Product List"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ffaa00;\">Warehouse Management</span></p></body></html>"))
